baseURL: https://hugo-theme-salt.okdyy75.com/
languageCode: ja
theme: hugo-theme-salt
title: 後悔しない家づくりのための重要ポイント
copyright: © 2024 後悔しない家づくりのための重要ポイント
author:
  name: 福の家マスター
  email: my_email@example.com
  url: https://example.com/my_url
googleAnalytics:
disqusShortname:

taxonomies:
  category: categories
  tag: tags
  pickup: pickups
  archive: archives

disablePathToLower: true
hasCJKLanguage: true
summaryLength: 200
pagination:
  pagerSize: 10

markup:
  goldmark:
    renderer:
      unsafe: true

related:
  includeNewer: true
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 90
    - name: date
      weight: 10
  threshold: 80
  toLower: false

module:
  mounts:
    - source: static
      target: static
    - source: node_modules/@fortawesome/fontawesome-free/css/all.min.css
      target: static/css/vendor/@fortawesome/fontawesome-free/css/all.min.css
    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/css/vendor/@fortawesome/fontawesome-free/webfonts
    - source: node_modules/github-markdown-css/github-markdown.css
      target: static/css/vendor/github-markdown-css/github-markdown.css
    # 検索に必要
    - source: node_modules/lunr/lunr.min.js
      target: static/js/vendor/lunr/lunr.min.js
    - source: node_modules/lunr-languages/lunr.stemmer.support.js
      target: static/js/vendor/lunr-languages/lunr.stemmer.support.js
    - source: node_modules/lunr-languages/tinyseg.js
      target: static/js/vendor/lunr-languages/tinyseg.js
    - source: node_modules/lunr-languages/lunr.ja.js
      target: static/js/vendor/lunr-languages/lunr.ja.js

params:
  description: 注文住宅、リフォームなどの家づくりを安心にサポートする情報サイト
  icon: image/icon.png
  images:
    - image/og_large.png
  notFoundImage: image/404.png
  dafaultNoimage: image/default_noimage.png
  newArticleLimit: 5
  rankingArticleLimit: 5
  relatedArticleLimit: 2
  imageQuality: 75
  profile:
    name: 福の家マスター
    description: 注文住宅、新築平屋、間取りプラン、リフォーム、資金計画、土地探しなどで後悔しないための情報を詳しく発信しています。
    icon: image/profile_icon_fukunoya.webp
    
  tocCollapsed: true  # ← true = 折りたたみ（初期状態）、false = 開いた状態

menu:
  header:
    - name: 注文住宅
      identifier: house
      weight: -100

    - name: リフォーム
      identifier: reform
      weight: -90

    - name: 土地活用
      identifier: land
      weight: -80

    - name: 空き家解決
      identifier: vacant
      weight: -70

    - name: 物件情報
      identifier: property
      weight: -60

    - name: Home
      url: "/"
      weight: 0

  house:
    - name: 【無料】家づくり計画書の一括見積
      url: "https://townlife-aff.com/link.php?i=645b4ba18234f&m=675598c315568"
      weight: 1
    - name: 【無料】間取りプラン作成
      url: "https://townlife-aff.com/link.php?i=5f2370a957a9b&m=675598c315568"
      weight: 2
    - name: 【無料】平屋住宅づくり
      url: "https://townlife-aff.com/link.php?i=5a6fd184815fb&m=675598c315568" 
      weight: 3
    - name: 【無料】土地探し
      url: "https://townlife-aff.com/link.php?i=5ff3f84eb12b4&m=675598c315568"
      weight: 4

  reform:
    - name: 【無料】リフォーム見積比較 300万円が200万円も!
      url: "https://townlife-aff.com/link.php?i=6552fc75c5f29&m=675598c315568"
      weight: 1
    - name: 【無料】リフォーム エクステリア・外構
      url: "https://townlife-aff.com/link.php?i=5af29474c8a10&m=675598c315568"
      weight: 2
    - name: 【無料】リフォーム シロアリ
      url: "https://townlife-aff.com/link.php?i=646ada4dbba74&m=675598c315568"
      weight: 3
  land:
    - name: 【無料】最適な土地活用の提案
      url: "https://townlife-aff.com/link.php?i=5a7127c9e2515&m=675598c315568"

  vacant:
    - name: 【無料】空き家解決診断
      url: "https://townlife-aff.com/link.php?i=67aeb70c15445&m=675598c315568"

  property:
    - name: 【無料】ネット未公開の物件情報一括サービス
      url: "https://townlife-aff.com/link.php?i=5a054bef01420&m=675598c315568"
          
  sidebar:
    - name: 注文住宅
      url: /categories/注文住宅
      pre: <i class="fa-2x fas fa-book"></i>
      weight: -100
    - name: リフォーム
      url: /categories/リフォーム
      pre: <i class="fa-2x fas fa-cog"></i>
      weight: -90
    - name: 土地活用
      url: /categories/土地活用
      pre: <i class="fa-2x fas fa-laptop-code"></i>
      weight: -80
    - name: 空き家解決
      url: /categories/空き家解決
      pre: <i class="fa-2x fas fa-mobile-alt"></i>
      weight: -70
    - name: 物件情報
      url: /categories/物件情報
      pre: <i class="fa-2x fas fa-wrench"></i>
      weight: -60
    - name: Home
      url: "/"
      pre: <i class="fa-2x fab fa-safari"></i>
      weight: -0
    
  footer:
    - name: このサイトについて
      url: /about
      weight: -100
      params:
        position: left
    - name: お問い合わせ
      url: /contact
      weight: -90
      params:
        position: left
    - name: プライバシーポリシー
      url: /privacy-policy
      weight: -100
      params:
        position: right
    - name: 特商法表記
      url: /legal
      weight: -90
      params:
        position: right
theme = "salt"
theme = "salt"
